### ISSUE TITLE
Multiple Calls

### ISSUE THREAD

**Issue by ryanscdavis** [yuanqing/load-google-maps-api#12]
Thanks for sharing the code!

However, there are issues when the function is called multiple times before the api has loaded. This may happen if there are multiple components that require the api. I have run into this using Vue but seems like it could happen with any component-based framework.

First, for multiple calls, multiple promises are being generated, but only get resolved during the callback function, which gets deleted after the first resolve. I would suggest saving the initial promise, and returning it on subsequent calls.

Second, there is no check to see if the script already exists, so it will get appended a second time while waiting for the first to resolve. A simple document.getElementById could check for this.

**Comment by Spone** [comment]
Same problem here.

> You have included the Google Maps API multiple times on this page. This may cause unexpected errors.
uncaught exception: InvalidValueError: __googleMapsApiOnLoadCallback is not a function

**Comment by yuanqing** [comment]
Thanks @ryanscdavis and @Spone for reporting this!

> I would suggest saving the initial promise, and returning it on subsequent calls.

Just cut a `1.3.1` with the above suggested fix, which should solve this issue.

**Comment by Spone** [comment]
Thank you!

Also, I noticed that you add the `script` tag to the `body`. Is there a specific reason?

I use [Turbolinks](https://github.com/turbolinks/turbolinks) and every script included in the body is run every time I navigate to a new page. Adding the `script` to the `head` would fix it.

**Comment by yuanqing** [comment]
Closing given that `1.3.1` has solved this issue
