### ISSUE TITLE
IE did not support Promise

### ISSUE THREAD

**Issue by xgtxxxx** [yuanqing/load-google-maps-api#2]
Should add "var Promise = require('es6-promise').Promise;" to index.js to fix this issue.

**Comment by yuanqing** [comment]
@xgtxxxx This library assumes that a Promise implementation is available. To support IE or other older browsers, you would have to [include your own `Promise` polyfill](https://github.com/stefanpenner/es6-promise#auto-polyfill).

```es6
require('es6-promise').polyfill();

import loadGoogleMapsAPI from 'load-google-maps-api';

loadGoogleMapsAPI().then((googleMaps) => {
  console.log(googleMaps); //=> Object { Animation: Object, ...
}).catch((err) => {
  console.error(err);
});
```
