### ISSUE TITLE
Feat proposal  | Extend to add google maps extended libraries

### ISSUE THREAD

**Issue by DanielaValero** [yuanqing/load-google-maps-api#6]
There are some libraries, that help the users to do some complex operations easier. They are listed here:
http://googlemaps.github.io/libraries

When the user needs to use any of these libraries, they would still need to do it in the manual way. However this library has the potential to give also that flexibility to the user, so they can decide which library to add to the project.

What do you think? Would it be a scope for this package? If so, I'd be glad to make a PR

**Comment by yuanqing** [comment]
@DanielaValero 

Currently `load-google-maps-api` already allows loading of [additional libraries](https://developers.google.com/maps/documentation/javascript/libraries) (libraries provided by Google Maps, not *third-party* external libraries) via `options.libraries`. Loading of third-party libraries seem to be outside the scope of this module.
