### ISSUE TITLE
Access extra libraries

### ISSUE THREAD

**Issue by strarsis** [yuanqing/load-google-maps-api#7]
I want to use the Google API PlacesService, therefore I passed `libraries: ['places']` to load-google-maps-api constructor. How can I now access it? The parameter passed to callback when Google Maps is loaded doesn't seem to contain a reference to e.g. PlacesService.

**Comment by broskees** [comment]
@strarsis Did you ever figure it out? I'm curious about the same thing.

My syntax is as follows:
```
loadGoogleMapsApi([{
  libraries: ["places"],
}]).then(function (googleMaps){
  // code here ...
  var service = new googleMaps.places.PlacesService(map);
}).catch(function (error) {
  console.error(error)
});
```
Returns in console:
`[Error] TypeError: undefined is not an object (evaluating 'new googleMaps.places.PlacesService')`

**Comment by strarsis** [comment]
@broskees: Not really yet, the code is still commented out.
Though after further inspecting the code, it appears that it should 
be accessible via `window.google.places` after the promise resolved.

**Comment by yuanqing** [comment]
@strarsis @broskees

The `loadGoogleMapsApi` promise resolves to the `window.google.maps` object. This works for me:

> [**CodePen**](https://codepen.io/anon/pen/VXzxKX?editors=1111)

```js
const loadGoogleMapsApi = require('load-google-maps-api')

loadGoogleMapsApi({ libraries: ['places'] })
  .then(function(googleMaps) {
    console.log(new googleMaps.places.PlacesService())
  })
  .catch(function(error) {
    console.error(error)
  })
```
